name: Extension Deployment
on:
  workflow_call:
    inputs:
      # The name of the extension
      extension_name:
        required: true
        type: string
      # DuckDB version to build against
      duckdb_version:
        required: true
        type: string
      # ';' separated list of architectures to exclude, for example: 'linux_amd64;osx_arm64'
      exclude_archs:
        required: false
        type: string
        default: ""
      # Whether to upload this deployment as the latest. This may overwrite a previous deployment.
      deploy_latest:
        required: false
        type: boolean
        default: false
      # Whether to upload this deployment under a versioned path. These will not be deleted automatically
      deploy_versioned:
        required: false
        type: boolean
        default: false
      # Postfix added to artifact names. Can be used to guarantee unique names when this workflow is called multiple times
      artifact_postfix:
        required: false
        type: string
        default: ""
      # Override the default deploy script with a custom script
      deploy_script:
        required: false
        type: string
        default: "./scripts/extension-upload.sh"
      # Override the default matrix parse script with a custom script
      matrix_parse_script:
        required: false
        type: string
        default: "./duckdb/scripts/modify_distribution_matrix.py"

jobs:
  generate_matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      deploy_matrix: ${{ steps.parse-matrices.outputs.deploy_matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Checkout DuckDB to version
        run: |
          cd duckdb
          git checkout ${{ inputs.duckdb_version }}

      - id: parse-matrices
        run: |
          python3 ${{ inputs.matrix_parse_script }} --input ./duckdb/.github/config/distribution_matrix.json --deploy_matrix --output deploy_matrix.json --exclude "${{ inputs.exclude_archs }}" --pretty
          deploy_matrix="`cat deploy_matrix.json`"
          echo deploy_matrix=$deploy_matrix >> $GITHUB_OUTPUT
          echo `cat $GITHUB_OUTPUT`

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: generate_matrix
    if: ${{ needs.generate_matrix.outputs.deploy_matrix != '{}' && needs.generate_matrix.outputs.deploy_matrix != '' }}
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.deploy_matrix)}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Checkout DuckDB to version
        run: |
          cd duckdb
          git checkout ${{ inputs.duckdb_version }}

      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.extension_name }}-${{ inputs.duckdb_version }}-extension-${{matrix.duckdb_arch}}${{inputs.artifact_postfix}}${{startsWith(matrix.duckdb, 'wasm') && '.wasm' || ''}}
          path: |
            /tmp/extension

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.6.1
        env:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
        if: ${{ env.key != '' }}
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          UPLOAD_BASE_PATH: ${{ secrets.UPLOAD_BASE_PATH }}
        run: |
          git config --global --add safe.directory '*'
          cd duckdb
          git fetch --tags
          export DUCKDB_VERSION=`git tag --points-at HEAD`
          export DUCKDB_VERSION=${DUCKDB_VERSION:=`git log -1 --format=%h`}
          cd ..
          if [[ "$SSH_HOST" == "" ]] ; then
            echo 'No key set, skipping'
          elif [[ "$GITHUB_REF" =~ ^(refs/tags/v.+)$ ]] ; then
            ./scripts/extension-upload.sh prql ${{ github.ref_name }} $DUCKDB_VERSION ${{matrix.duckdb_arch}} true
          elif [[ "$GITHUB_REF" =~ ^(refs/heads/main)$ ]] ; then
            ./scripts/extension-upload.sh prql `git log -1 --format=%h` $DUCKDB_VERSION ${{matrix.duckdb_arch}} false
          fi
