name: Wasm
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  linux:
    name: WASM Release
    runs-on: ubuntu-latest
    container: 'ubuntu:18.04'
    env:
      GEN: ninja

    steps:
    - name: Install required ubuntu packages
      run: |
        apt-get update -y -qq
        apt-get install -y -qq software-properties-common
        add-apt-repository ppa:git-core/ppa
        apt-get update -y -qq
        apt-get install -y -qq ninja-build make gcc-multilib g++-multilib libssl-dev wget openjdk-8-jdk zip maven unixodbc-dev libc6-dev-i386 lib32readline6-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip build-essential checkinstall libffi-dev curl libz-dev openssh-client

    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: 'latest'

    - name: Validate emsdk
      run: which emmake

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | bash -s -- -y
    
    - name: Install Rust Cross-compilation targets
      run: $HOME/.cargo/bin/rustup target add wasm32-unknown-emscripten

    - name: Install Git 2.18.5
      run: |
        wget https://github.com/git/git/archive/refs/tags/v2.18.5.tar.gz
        tar xvf v2.18.5.tar.gz
        cd git-2.18.5
        make
        make prefix=/usr install
        git --version

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'

    - uses: ./duckdb/.github/actions/ubuntu_18_setup
      
      # Build extension
    - name: Build extension
      run: |
        make wasm_mvp
